#pragma once

#define IOCTL_PG_ADD_PID        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PG_REMOVE_PID     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PG_CLEAR_ALL      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PG_ENABLE_SELF_DEFENSE    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PG_DISABLE_SELF_DEFENSE   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PG_ALLOW_UNLOAD   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PG_ADD_WHITELIST  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)

#pragma pack(push, 1)

struct PG_PROTECTION_CONFIG {
    unsigned int Flags;
    unsigned int Reserved;
};

#define PG_FLAG_PROTECT_VM_READ     0x00000001
#define PG_FLAG_PROTECT_VM_WRITE    0x00000002
#define PG_FLAG_PROTECT_VM_OP       0x00000004
#define PG_FLAG_PROTECT_TERMINATE   0x00000008
#define PG_FLAG_PROTECT_THREADS     0x00000010
#define PG_FLAG_ALLOW_QUERY_INFO    0x00000020

#define PG_FLAG_DEFAULT (PG_FLAG_PROTECT_VM_WRITE | PG_FLAG_PROTECT_VM_OP | \
                         PG_FLAG_PROTECT_TERMINATE | PG_FLAG_PROTECT_THREADS | \
                         PG_FLAG_ALLOW_QUERY_INFO)

#pragma pack(pop)
